[devbox]
image=ghcr.io/phoreos/devbox-distrobox:latest
# pull=false
# additional_packages=
exported_apps=code

# init_hooks=git clone https://github.com/tuo-user/dotfiles.git ~/.dotfiles && ~/.dotfiles/install.sh
